#!/bin/bash

# uncomment for debug
# set -x

if [ $# -gt 2 ]
then
	printf "Wrong number of arguments\n"
	printf "Usage:\n"
	printf "    backup SRC DEST\n"
	printf "or  backup\n"
	exit 1
fi

printf "Running backup...\n"

if [ $# -eq 2 ]
then
	rsync -vrp $1 $2
fi

if [ $# -eq 0 ]
then
	read -p 'Source: ' src
	read -p 'Destination: ' dest
	rsync -vrp $src $dest
fi

printf "\nSuccess!\n"
