#!/bin/bash

# uncomment for debug
#set -x

# can be added to by editing this file
SYNC_OPTS="-urpq"

# can be changed with '-e' option
ERR_FILE="backup_errs.log"

error_trig() {
	printf "%s\n" "$1" 1>&2
	exit 1
}

backup() {
	printf "%s\n" "Running backup..."
	rsync $SYNC_OPTS "$1" "$2" 2> $ERR_FILE 
	if [[ ! "$?" = "0" ]]; then
		# something went wrong
		error_trig "Error occurred while backing up. Check messages in $ERR_FILE"
	fi
}

make_dir() {
	while true; do
		read -p "$1 doesn't exist, create it? [Y/n] " yn
		case $yn in
			[Yy])
				mkdir -p "$1"
				break
				;;
			[Nn])
				error_trig "Please create destination dir and try again."
				;;
			*)
				printf "%s\n" "Please enter [Yy] or [Nn]"
				;;
		esac
	done
}

check_dirs() {
	if [[ -e "$1" ]]; then
		if [[ ! -e "$2" ]]; then
			make_dir "$2"
		fi
	else
		error_trig "Error: $1 doesn't exist."
	fi
}

do_backup_with_args() {	
	check_dirs "$1" "$2"
	
	# no errors at this point, do backup
	backup "$1" "$2"
}

do_backup_wo_args() {
	read -p 'Source: ' src
	read -p 'Destination: ' dest
	
	check_dirs $src $dest
	
	# no errors at this point, do backup
	backup "$src" "$dest"
}

usage() {
	printf "%s\n" "Usage: backup [OPTIONS] [SRC DEST]"
	printf "%s\n" "Examples:         backup $HOME/bin /tmp/backup"
	printf "%s\n" "                  backup"
	printf "%s\n" "Options:"
	printf "%s\n" "-h, --help                    Print this help."
	printf "%s\n" "-e, --err_file err_file.txt   Output errors to the provided file."
	printf "%s\n" "-v, --verbose                 Turns on verbose logging."
}

get_args() {
	if [[ $# -eq 0 ]]; then
		do_backup_wo_args
	else
		while [[ "$1" != "" ]]; do
			case "$1" in
				-h | --help)
					usage
					exit
					;;
				-e | --err_file)
					shift
					ERR_FILE="$1"
					;;
				-v | --verbose)
					SYNC_OPTS="-urpv"
					;;
			esac
			shift
		done
	fi
}

main() {
	get_args "$@"

	printf "\n%s\n" "Success!"
}

main "$@"
